#!/bin/bash

# this is a config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#5A8E3A'

# remove all existing keybindings
hc keyunbind --all

#terminal
term=urxvt

# keybindings
Mod=Mod4   # Use the super key as the main modifier
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close

# apps
hc keybind $Mod-Return spawn $term
hc keybind $Mod-w spawn google-chrome-stable

# tags
TAG_NAMES=( terminals web development media files graphics games torrent float other )
TAG_KEYS=( {1..9} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-v split vertical 0.5
hc keybind $Mod-b split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# resizing
RESIZESTEP=0.01
hc keybind $Mod-Control-Left resize left +$RESIZESTEP
hc keybind $Mod-Control-Down resize down +$RESIZESTEP
hc keybind $Mod-Control-Up resize up +$RESIZESTEP
hc keybind $Mod-Control-Right resize right +$RESIZESTEP

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc keybind $Mod-BackSpace cycle_monitor
hc keybind $Mod-Tab cycle_all +1
hc keybind $Mod-Shift-Tab cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-Left focus left
hc keybind $Mod-Down focus down
hc keybind $Mod-Up focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-i jumpto urgent
hc keybind $Mod-Shift-Left shift left
hc keybind $Mod-Shift-Down shift down
hc keybind $Mod-Shift-Up shift up
hc keybind $Mod-Shift-Right shift right

# look
hc set frame_border_width 0
hc set window_border_width 8
hc set window_border_inner_width 0
hc set window_border_normal_color '#353535'
hc set window_border_active_color '#454545'
hc set always_show_frame 0
hc set frame_gap 64

# add overlapping window borders
hc set window_gap 0
hc set frame_padding -1
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# transparency is needed for useless gaps
hc set frame_bg_transparent 0
hc set frame_active_opacity 1
hc set frame_normal_opacity 1

# rules for popups
# put them on "float" tag
hc unrule -F
hc rule focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' tag=float pseudotile=on focus=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' tag=float focus=on
hc rule class='zenity' tag=float focus=on

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# autorun a few programs in background
nitrogen --restore &
xflux -z 97520 &

# windowed games
# hc rule class=love tag=games index=01 pseudotile=on
# hc rule class=sfml tag=games index=01 pseudotile=on
# hc rule class=love9 tag=games index=01 pseudotile=on
# hc rule class=lt-love tag=games index=01 pseudotile=on

# graphics
# hc load graphics '(split horizontal:0.850000:0(split horizontal:0.200000:1(clients vertical:0)(clients grid:0))(clients vertical:0))'
# center all other gimp windows on gimp tag
# hc rule class=Gimp tag=graphics index=01 pseudotile=on
# hc rule class=Gimp windowrole~'gimp-(image-window|toolbox|dock)' pseudotile=off
# hc rule class=Gimp windowrole=gimp-toolbox focus=off index=00
# hc rule class=Gimp windowrole=gimp-dock focus=off index=1

# terminals
hc load terminals '(split horizontal:0.950000:0 (split horizontal:0.060000:1 (clients vertical:0) (split horizontal:0.500000:1 (split vertical:0.710000:0 (clients vertical:0 0x1a00003) (clients vertical:0 0x1600003)) (split vertical:0.225000:1 (clients vertical:0 0x1400003) (clients vertical:0 0x1800003)))) (clients vertical:0))'

# assign windows to their frames
hc rule title=weechat tag=terminals index=010
hc rule title=player tag=terminals index=0101
hc rule title=htop tag=terminals index=0110
hc rule title=termtop tag=terminals index=01111

# autorun a few programs in terminals
pgrep "${term} -T weechat" -f > /dev/null || $term -T weechat -e 'weechat' &
pgrep "${term} -T player" -f > /dev/null || $term -T player -e 'ncmpcpp' &
pgrep "${term} -T htop" -f > /dev/null || $term -T htop -e 'htop' &
pgrep "${term} -T termtop" -f > /dev/null || $term -T termtop &

# web
# hc load web '(split horizontal:0.690000:1 (clients vertical:0 0x2200003) (split vertical:0.640000:0 (clients vertical:0 0x2400003 0x2600003) (clients vertical:0 0x1c00003)))'

# development
# hc load development '(split horizontal:0.690000:1 (clients vertical:0 0x2200003) (split vertical:0.640000:0 (clients vertical:0 0x2400003 0x2600003) (clients vertical:0 0x1c00003)))'

# pad 25px from bottom and from top, for panels
hc pad 0 25 0 0

# find and run the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
$panel 0 &

# volume keys
# hc keybind XF86AudioRaiseVolume spawn $HOME/scripts/pavolume-dzen.sh -i 2
# hc keybind XF86AudioLowerVolume spawn $HOME/scripts/pavolume-dzen.sh -d 2

# print screen osd
hc keybind Print spawn $HOME/scripts/dmenu-screen

## floating windows handling:
# https://reddit.com/r/unixporn/comments/1l1eaa/archherbstluftwm_single_floating_windowspopups/
# create a virtual monitor for floating windows
a=$(herbstclient list_monitors | grep two)
if [ "$a" == "" ]; then
	hc floating float on

	hc add_monitor 1366x768 float two

	hc lock_tag two
fi
